travis.yml changes

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,13 +1,35 @@
-language: haskell
+# This is adapted from
+# https://github.com/hvr/multi-ghc-travis
+
+# Don't set language:haskell
+
+env:
+  - GHCVER=7.4.1
+  - GHCVER=7.6.3
+
 before_install:
-  - make penny.cabal
+  - travis_retry sudo apt-add-repository -y ppa:hvr/ghc
+  - travis_retry sudo apt-get update
+  - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
+  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 
 install:
-  - cabal install --only-dependencies
-
-before_script:
-  - cabal configure --enable-tests
+  - cabal-1.18 update
+  - make penny.cabal
+  - cabal-1.18 install --only-dependencies --enable-tests
 
 script:
-  - cabal build
+  - cabal-1.18 configure --enable-tests -v2
+  - cabal-1.18 build
   - dist/build/penny-test/penny-test
+  - cabal-1.18 check
+  - cabal-1.18 sdist
+  - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+    cd dist/;
+    if [-f "$SRC_TGZ" ]; then
+      cabal-1.18 install "$SRC_TGZ";
+    else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+    fi
+
